name: Deploy

on:
  push:
    branches:
      - master  # or the branch you want to use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Updated to v3, compatible with Node 16

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3, compatible with Node 16
      with:
        node-version: '16'  # Confirmed Node.js version to use

    - name: Install dependencies
      run: npm install

    - name: Run deploy
      run: npm run deploy
